apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "bruco.name" . }}-role
rules:
- apiGroups: [""]
  resources: ["services", "pods", "events", "configmaps"]
  verbs: ["*"]
- apiGroups: ["apps", "extensions"]
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: ["bruco.ferama.github.io"]
  resources: ["brucos", "brucos/status"]
  verbs: ["*"]