kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "bruco.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "bruco.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "bruco.name" . }}-role
  apiGroup: rbac.authorization.k8s.io