processor:
  workDir: "./hack/examples/lambda"
  # OPTIONAL: defult handler
  moduleName: handler
  workers: 3
  env:
    VAR1: var1-value
    VAR2: var2-value

source:
  kind: kafka
  brokers:
    - localhost:9092
  topics:
    - test1
    - test2
  # OPTIONAL: default latest
  offset: latest # values: latest, earliest
  consumerGroup: my-consumer-group
  # OPTIONAL: default range
  balanceStrategy: range # values: range, sticky, roundrobin
  # NOTE: the async handler version will not guarantee
  # messages handling order between same partition
  asyncHandler: true

sink:
  kind: kafka
  brokers:
    - localhost:9092
  topic: test-out
  # OPTIONAL: target partition
  partition: 42
  # OPTIONAL: default hash if partition is not defined
  partitioner: hash # values: manual, hash, random
