processor:
  handlerURL: ./hack/examples/basic
  # handlerURL: ./hack/examples/basic
  # handlerURL: http://localhost:5000/handler.zip
  # handlerURL: http://localhost:5000/handler/handler.py
  # handlerURL: https://raw.githubusercontent.com/ferama/bruco/main/hack/examples/basic/handler.py
  moduleName: handler
  # moduleName: myhandler.handler
  workers: 4
  env:
    - name: VAR1
      value: var1-value
    - name: VAR2
      value: var2-value

source:
  kind: nats
  serverUrl: localhost:4222
  queueGroup: test
  subject: in.sub

sink:
  kind: nats
  serverUrl: localhost:4222
  subject: out.sub