processor:
  lambdaPath: "./hack/lambda"
  workers: 3

source:
  kind: kafka
  brokers:
    - localhost:9092
  topics:
    - test1
    - test2
  # OPTIONAL: default latest
  offset: latest # values: latest, earliest
  consumerGroup: my-consumer-group
  # OPTIONAL: default range
  balanceStrategy: range # values: range, sticky, roundrobin
  # NOTE: the async handler version will not guarantee
  # messages handling order between same partition
  asyncHandler: true

sink:
  kind: kafka
  brokers:
    - localhost:9092
  topic: test-out
  # OPTIONAL: target partition
  partition: 42
  # OPTIONAL: partitioner
  partitioner: manual # values: manual, hash, random
