processor:
  lambdaPath: "./hack/lambda"
  workers: 3

source:
  kind: kafka
  brokers:
    - localhost:9092
  topics:
    - test
  consumerGroup: my-consumer-group
  balanceStrategy: range
  # NOTE: the async handler version will not guarantee
  # messages handling order between same partition
  asyncHandler: true

sink:
  kind: kafka
  brokers:
    - localhost:9092
  topic: test-out
