baseURL = "https://ferama.github.io/bruco/"
languageCode = "en-us"
title = "Bruco 🐛"

[menu]
    [[menu.main]]
        identifier = "getting-started"
        name = "Getting started on k8s"
        url = "/getting-started"
        weight = 1
     [[menu.main]]
        identifier = "config"
        name = "Config"
        url = "/config-file"
        weight = 2
    [[menu.main]]
        parent = "config"
        identifier = "sources"
        name = "Sources"
        url = "/sources"
        weight = 1
    [[menu.main]]
        parent = "config"
        identifier = "sinks"
        name = "Sinks"
        url = "/sinks"
        weight = 2
    [[menu.main]]
        parent = "config"
        identifier = "processor"
        name = "Processor"
        url = "/processor"
        weight = 3
   
    [[menu.main]]
        identifier = "github"
        name = "<i class='fab fa-github'></i> Star Bruco on Github"
        url = "https://github.com/ferama/bruco"
        weight = 100

[params]
    themeColor = "theme-base-0d"
    # description = " "
    description = "Easy build streaming pipelines. Handle business logic in python"
