baseURL = "https://ferama.github.io/bruco/"
languageCode = "en-us"
title = "Bruco 🐛"
theme = "hugo-theme-learn"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
landingPageURL = "/bruco"
landingPageName = "<i class='fas fa-home'></i> Home"
# make template think this is a multilang site
[Languages.it]

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/ferama/bruco"
weight = 10

[params]
disableLanguageSwitchingButton = true
disableLandingPage = false
disableNextPrev = true
author = "Marco Ferragina"
description = "Easy build streaming pipelines. Handle business logic in python"