apiVersion: bruco.ferama.github.io/v1alpha1
kind: BrucoProject
metadata:
  name: example-bruco-project
spec:
  name: "example project"
  brucos:
    - replicas: 1
      functionURL: https://github.com/ferama/bruco/raw/main/examples/zipped/sentiment.zip
      # functionURL: https://github.com/ferama/bruco/raw/main/examples/zipped/basic.zip
      stream:
        processor:
          workers: 2
        source:
          kind: http
          ignoreProcessorResponse: false
