apiVersion: bruco.ferama.github.io/v1alpha1
kind: Bruco
metadata:
  name: example-bruco
spec:
  replicas: 1
  # functionURL: https://github.com/ferama/bruco/raw/main/hack/examples/zipped/sentiment.zip
  functionURL: https://github.com/ferama/bruco/raw/main/hack/examples/zipped/basic.zip
  conf:
    processor:
      workers: 1
    source:
      kind: http
      port: 8080
      ignoreProcessorResponse: true
